# Generated by Django 4.2.2 on 2023-06-18 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bibleApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='church',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
