# Generated by Django 4.2.2 on 2023-06-22 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibleApp', '0002_alter_church_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrayerSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('total_time', models.DurationField(null=True)),
                ('voice_time', models.DurationField(null=True)),
            ],
        ),
    ]
