# Generated by Django 4.2.2 on 2023-09-03 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibleApp', '0002_customuser_age_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='community',
            name='church',
        ),
        migrations.RemoveField(
            model_name='community',
            name='members',
        ),
        migrations.RemoveField(
            model_name='team',
            name='community',
        ),
        migrations.RemoveField(
            model_name='team',
            name='lead',
        ),
        migrations.RemoveField(
            model_name='team',
            name='members',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_church_member',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Church',
        ),
        migrations.DeleteModel(
            name='Community',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
