# Generated by Django 4.2.2 on 2023-09-03 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibleApp', '0003_remove_community_admin_remove_community_church_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_church_admin',
            field=models.BooleanField(default=False),
        ),
    ]
