# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import prayer_tracker_pb2 as prayer__tracker__pb2


class PrayerTrackerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartPrayer = channel.unary_unary(
                '/prayertracker.PrayerTrackerService/StartPrayer',
                request_serializer=prayer__tracker__pb2.StartPrayerRequest.SerializeToString,
                response_deserializer=prayer__tracker__pb2.StartPrayerResponse.FromString,
                )
        self.EndPrayer = channel.unary_unary(
                '/prayertracker.PrayerTrackerService/EndPrayer',
                request_serializer=prayer__tracker__pb2.EndPrayerRequest.SerializeToString,
                response_deserializer=prayer__tracker__pb2.EndPrayerResponse.FromString,
                )
        self.PrayerUpdates = channel.unary_stream(
                '/prayertracker.PrayerTrackerService/PrayerUpdates',
                request_serializer=prayer__tracker__pb2.PrayerRequest.SerializeToString,
                response_deserializer=prayer__tracker__pb2.PrayerUpdateResponse.FromString,
                )
        self.ProcessVoiceStream = channel.stream_stream(
                '/prayertracker.PrayerTrackerService/ProcessVoiceStream',
                request_serializer=prayer__tracker__pb2.ProcessVoiceRequest.SerializeToString,
                response_deserializer=prayer__tracker__pb2.ProcessVoiceResponse.FromString,
                )


class PrayerTrackerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StartPrayer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EndPrayer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PrayerUpdates(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProcessVoiceStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PrayerTrackerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartPrayer': grpc.unary_unary_rpc_method_handler(
                    servicer.StartPrayer,
                    request_deserializer=prayer__tracker__pb2.StartPrayerRequest.FromString,
                    response_serializer=prayer__tracker__pb2.StartPrayerResponse.SerializeToString,
            ),
            'EndPrayer': grpc.unary_unary_rpc_method_handler(
                    servicer.EndPrayer,
                    request_deserializer=prayer__tracker__pb2.EndPrayerRequest.FromString,
                    response_serializer=prayer__tracker__pb2.EndPrayerResponse.SerializeToString,
            ),
            'PrayerUpdates': grpc.unary_stream_rpc_method_handler(
                    servicer.PrayerUpdates,
                    request_deserializer=prayer__tracker__pb2.PrayerRequest.FromString,
                    response_serializer=prayer__tracker__pb2.PrayerUpdateResponse.SerializeToString,
            ),
            'ProcessVoiceStream': grpc.stream_stream_rpc_method_handler(
                    servicer.ProcessVoiceStream,
                    request_deserializer=prayer__tracker__pb2.ProcessVoiceRequest.FromString,
                    response_serializer=prayer__tracker__pb2.ProcessVoiceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'prayertracker.PrayerTrackerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PrayerTrackerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StartPrayer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/prayertracker.PrayerTrackerService/StartPrayer',
            prayer__tracker__pb2.StartPrayerRequest.SerializeToString,
            prayer__tracker__pb2.StartPrayerResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def EndPrayer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/prayertracker.PrayerTrackerService/EndPrayer',
            prayer__tracker__pb2.EndPrayerRequest.SerializeToString,
            prayer__tracker__pb2.EndPrayerResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PrayerUpdates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/prayertracker.PrayerTrackerService/PrayerUpdates',
            prayer__tracker__pb2.PrayerRequest.SerializeToString,
            prayer__tracker__pb2.PrayerUpdateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ProcessVoiceStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/prayertracker.PrayerTrackerService/ProcessVoiceStream',
            prayer__tracker__pb2.ProcessVoiceRequest.SerializeToString,
            prayer__tracker__pb2.ProcessVoiceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
