# Generated by Django 4.2.2 on 2023-10-03 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prayer_sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyDevotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField()),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_devotions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Daily Devotions',
            },
        ),
        migrations.CreateModel(
            name='UserPrayerSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('voice_detected', models.BooleanField()),
                ('active', models.BooleanField(default=False)),
                ('daily_devotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prayer_sessions.dailydevotion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Prayer Sessions',
            },
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='dailydevotion',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_devotions', to='prayer_sessions.supervisor'),
        ),
        migrations.AlterField(
            model_name='prayerrecord',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prayer_sessions.userprayersession'),
        ),
        migrations.DeleteModel(
            name='PrayerSession',
        ),
    ]
