# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

# import bible_pb2 as bible__pb2
from . import bible_pb2 as bible__pb2


class BibleServiceStub(object):
    """Service definition for the Bible app.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetBibleVersions = channel.unary_unary(
                '/bible.BibleService/GetBibleVersions',
                request_serializer=bible__pb2.Empty.SerializeToString,
                response_deserializer=bible__pb2.BibleVersionList.FromString,
                )
        self.GetBooksInVersion = channel.unary_unary(
                '/bible.BibleService/GetBooksInVersion',
                request_serializer=bible__pb2.GetBooksRequest.SerializeToString,
                response_deserializer=bible__pb2.BibleBookList.FromString,
                )
        self.GetChaptersInBook = channel.unary_unary(
                '/bible.BibleService/GetChaptersInBook',
                request_serializer=bible__pb2.GetChaptersRequest.SerializeToString,
                response_deserializer=bible__pb2.BibleChapterList.FromString,
                )
        self.GetVersesInChapter = channel.unary_unary(
                '/bible.BibleService/GetVersesInChapter',
                request_serializer=bible__pb2.GetVersesRequest.SerializeToString,
                response_deserializer=bible__pb2.BibleVerseList.FromString,
                )
        self.GetVerse = channel.unary_unary(
                '/bible.BibleService/GetVerse',
                request_serializer=bible__pb2.GetVerseRequest.SerializeToString,
                response_deserializer=bible__pb2.BibleVerse.FromString,
                )


class BibleServiceServicer(object):
    """Service definition for the Bible app.
    """

    def GetBibleVersions(self, request, context):
        """Get a list of Bible versions.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBooksInVersion(self, request, context):
        """Get a list of books in a specific Bible version.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetChaptersInBook(self, request, context):
        """Get a list of chapters in a specific book of a Bible version.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVersesInChapter(self, request, context):
        """Get a list of verses in a specific chapter of a book in a Bible version.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVerse(self, request, context):
        """Get a specific verse in a chapter of a book in a Bible version.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BibleServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetBibleVersions': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBibleVersions,
                    request_deserializer=bible__pb2.Empty.FromString,
                    response_serializer=bible__pb2.BibleVersionList.SerializeToString,
            ),
            'GetBooksInVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBooksInVersion,
                    request_deserializer=bible__pb2.GetBooksRequest.FromString,
                    response_serializer=bible__pb2.BibleBookList.SerializeToString,
            ),
            'GetChaptersInBook': grpc.unary_unary_rpc_method_handler(
                    servicer.GetChaptersInBook,
                    request_deserializer=bible__pb2.GetChaptersRequest.FromString,
                    response_serializer=bible__pb2.BibleChapterList.SerializeToString,
            ),
            'GetVersesInChapter': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVersesInChapter,
                    request_deserializer=bible__pb2.GetVersesRequest.FromString,
                    response_serializer=bible__pb2.BibleVerseList.SerializeToString,
            ),
            'GetVerse': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVerse,
                    request_deserializer=bible__pb2.GetVerseRequest.FromString,
                    response_serializer=bible__pb2.BibleVerse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'bible.BibleService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BibleService(object):
    """Service definition for the Bible app.
    """

    @staticmethod
    def GetBibleVersions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bible.BibleService/GetBibleVersions',
            bible__pb2.Empty.SerializeToString,
            bible__pb2.BibleVersionList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetBooksInVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bible.BibleService/GetBooksInVersion',
            bible__pb2.GetBooksRequest.SerializeToString,
            bible__pb2.BibleBookList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetChaptersInBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bible.BibleService/GetChaptersInBook',
            bible__pb2.GetChaptersRequest.SerializeToString,
            bible__pb2.BibleChapterList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetVersesInChapter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bible.BibleService/GetVersesInChapter',
            bible__pb2.GetVersesRequest.SerializeToString,
            bible__pb2.BibleVerseList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetVerse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bible.BibleService/GetVerse',
            bible__pb2.GetVerseRequest.SerializeToString,
            bible__pb2.BibleVerse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
