# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bible.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x62ible.proto\x12\x05\x62ible\"\x07\n\x05\x45mpty\"\"\n\x0fGetBooksRequest\x12\x0f\n\x07version\x18\x01 \x01(\t\"3\n\x12GetChaptersRequest\x12\x0f\n\x07version\x18\x01 \x01(\t\x12\x0c\n\x04\x62ook\x18\x02 \x01(\t\"B\n\x10GetVersesRequest\x12\x0f\n\x07version\x18\x01 \x01(\t\x12\x0c\n\x04\x62ook\x18\x02 \x01(\t\x12\x0f\n\x07\x63hapter\x18\x03 \x01(\x05\"P\n\x0fGetVerseRequest\x12\x0f\n\x07version\x18\x01 \x01(\t\x12\x0c\n\x04\x62ook\x18\x02 \x01(\t\x12\x0f\n\x07\x63hapter\x18\x03 \x01(\x05\x12\r\n\x05verse\x18\x04 \x01(\x05\"$\n\x10\x42ibleVersionList\x12\x10\n\x08versions\x18\x01 \x03(\t\"\x1e\n\rBibleBookList\x12\r\n\x05\x62ooks\x18\x01 \x03(\t\"$\n\x10\x42ibleChapterList\x12\x10\n\x08\x63hapters\x18\x01 \x03(\x05\"3\n\x0e\x42ibleVerseList\x12!\n\x06verses\x18\x01 \x03(\x0b\x32\x11.bible.BibleVerse\"-\n\nBibleVerse\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\x12\x0e\n\x06number\x18\x02 \x01(\x05\x32\xd2\x02\n\x0c\x42ibleService\x12\x39\n\x10GetBibleVersions\x12\x0c.bible.Empty\x1a\x17.bible.BibleVersionList\x12\x41\n\x11GetBooksInVersion\x12\x16.bible.GetBooksRequest\x1a\x14.bible.BibleBookList\x12G\n\x11GetChaptersInBook\x12\x19.bible.GetChaptersRequest\x1a\x17.bible.BibleChapterList\x12\x44\n\x12GetVersesInChapter\x12\x17.bible.GetVersesRequest\x1a\x15.bible.BibleVerseList\x12\x35\n\x08GetVerse\x12\x16.bible.GetVerseRequest\x1a\x11.bible.BibleVerseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bible_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_EMPTY']._serialized_start=22
  _globals['_EMPTY']._serialized_end=29
  _globals['_GETBOOKSREQUEST']._serialized_start=31
  _globals['_GETBOOKSREQUEST']._serialized_end=65
  _globals['_GETCHAPTERSREQUEST']._serialized_start=67
  _globals['_GETCHAPTERSREQUEST']._serialized_end=118
  _globals['_GETVERSESREQUEST']._serialized_start=120
  _globals['_GETVERSESREQUEST']._serialized_end=186
  _globals['_GETVERSEREQUEST']._serialized_start=188
  _globals['_GETVERSEREQUEST']._serialized_end=268
  _globals['_BIBLEVERSIONLIST']._serialized_start=270
  _globals['_BIBLEVERSIONLIST']._serialized_end=306
  _globals['_BIBLEBOOKLIST']._serialized_start=308
  _globals['_BIBLEBOOKLIST']._serialized_end=338
  _globals['_BIBLECHAPTERLIST']._serialized_start=340
  _globals['_BIBLECHAPTERLIST']._serialized_end=376
  _globals['_BIBLEVERSELIST']._serialized_start=378
  _globals['_BIBLEVERSELIST']._serialized_end=429
  _globals['_BIBLEVERSE']._serialized_start=431
  _globals['_BIBLEVERSE']._serialized_end=476
  _globals['_BIBLESERVICE']._serialized_start=479
  _globals['_BIBLESERVICE']._serialized_end=817
# @@protoc_insertion_point(module_scope)
