# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import bible_service_pb2 as bible__service__pb2


class BibleServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetBibleVersions = channel.unary_unary(
                '/bible.BibleService/GetBibleVersions',
                request_serializer=bible__service__pb2.EmptyRequest.SerializeToString,
                response_deserializer=bible__service__pb2.BibleVersionList.FromString,
                )
        self.GetBooksInVersion = channel.unary_unary(
                '/bible.BibleService/GetBooksInVersion',
                request_serializer=bible__service__pb2.BibleVersionRequest.SerializeToString,
                response_deserializer=bible__service__pb2.BibleBookList.FromString,
                )
        self.GetChaptersInBook = channel.unary_unary(
                '/bible.BibleService/GetChaptersInBook',
                request_serializer=bible__service__pb2.BibleChapterRequest.SerializeToString,
                response_deserializer=bible__service__pb2.BibleChapterList.FromString,
                )
        self.GetVerseInChapter = channel.unary_unary(
                '/bible.BibleService/GetVerseInChapter',
                request_serializer=bible__service__pb2.BibleVerseRequest.SerializeToString,
                response_deserializer=bible__service__pb2.BibleVerseResponse.FromString,
                )
        self.CompareVerses = channel.unary_unary(
                '/bible.BibleService/CompareVerses',
                request_serializer=bible__service__pb2.CompareVersesRequest.SerializeToString,
                response_deserializer=bible__service__pb2.CompareVersesResponse.FromString,
                )


class BibleServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetBibleVersions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBooksInVersion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetChaptersInBook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVerseInChapter(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompareVerses(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BibleServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetBibleVersions': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBibleVersions,
                    request_deserializer=bible__service__pb2.EmptyRequest.FromString,
                    response_serializer=bible__service__pb2.BibleVersionList.SerializeToString,
            ),
            'GetBooksInVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBooksInVersion,
                    request_deserializer=bible__service__pb2.BibleVersionRequest.FromString,
                    response_serializer=bible__service__pb2.BibleBookList.SerializeToString,
            ),
            'GetChaptersInBook': grpc.unary_unary_rpc_method_handler(
                    servicer.GetChaptersInBook,
                    request_deserializer=bible__service__pb2.BibleChapterRequest.FromString,
                    response_serializer=bible__service__pb2.BibleChapterList.SerializeToString,
            ),
            'GetVerseInChapter': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVerseInChapter,
                    request_deserializer=bible__service__pb2.BibleVerseRequest.FromString,
                    response_serializer=bible__service__pb2.BibleVerseResponse.SerializeToString,
            ),
            'CompareVerses': grpc.unary_unary_rpc_method_handler(
                    servicer.CompareVerses,
                    request_deserializer=bible__service__pb2.CompareVersesRequest.FromString,
                    response_serializer=bible__service__pb2.CompareVersesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'bible.BibleService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BibleService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetBibleVersions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bible.BibleService/GetBibleVersions',
            bible__service__pb2.EmptyRequest.SerializeToString,
            bible__service__pb2.BibleVersionList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetBooksInVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bible.BibleService/GetBooksInVersion',
            bible__service__pb2.BibleVersionRequest.SerializeToString,
            bible__service__pb2.BibleBookList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetChaptersInBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bible.BibleService/GetChaptersInBook',
            bible__service__pb2.BibleChapterRequest.SerializeToString,
            bible__service__pb2.BibleChapterList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetVerseInChapter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bible.BibleService/GetVerseInChapter',
            bible__service__pb2.BibleVerseRequest.SerializeToString,
            bible__service__pb2.BibleVerseResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CompareVerses(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bible.BibleService/CompareVerses',
            bible__service__pb2.CompareVersesRequest.SerializeToString,
            bible__service__pb2.CompareVersesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
