# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: prayer_tracker.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14prayer_tracker.proto\x12\rprayertracker\"%\n\x12StartPrayerRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\"&\n\x13StartPrayerResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"#\n\x10\x45ndPrayerRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\"$\n\x11\x45ndPrayerResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\'\n\x14PrayerUpdatesRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\"_\n\x14PrayerUpdateResponse\x12\x17\n\x0fprayer_duration\x18\x01 \x01(\x05\x12\x16\n\x0evoice_duration\x18\x02 \x01(\x05\x12\x16\n\x0evoice_detected\x18\x03 \x01(\x08\"(\n\x15PrayerDurationRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\"*\n\x16PrayerDurationResponse\x12\x10\n\x08\x64uration\x18\x01 \x01(\x05\"\'\n\x14VoiceDurationRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\")\n\x15VoiceDurationResponse\x12\x10\n\x08\x64uration\x18\x01 \x01(\x05\x32\xcd\x03\n\rPrayerTracker\x12T\n\x0bStartPrayer\x12!.prayertracker.StartPrayerRequest\x1a\".prayertracker.StartPrayerResponse\x12N\n\tEndPrayer\x12\x1f.prayertracker.EndPrayerRequest\x1a .prayertracker.EndPrayerResponse\x12[\n\rPrayerUpdates\x12#.prayertracker.PrayerUpdatesRequest\x1a#.prayertracker.PrayerUpdateResponse0\x01\x12]\n\x0ePrayerDuration\x12$.prayertracker.PrayerDurationRequest\x1a%.prayertracker.PrayerDurationResponse\x12Z\n\rVoiceDuration\x12#.prayertracker.VoiceDurationRequest\x1a$.prayertracker.VoiceDurationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'prayer_tracker_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_STARTPRAYERREQUEST']._serialized_start=39
  _globals['_STARTPRAYERREQUEST']._serialized_end=76
  _globals['_STARTPRAYERRESPONSE']._serialized_start=78
  _globals['_STARTPRAYERRESPONSE']._serialized_end=116
  _globals['_ENDPRAYERREQUEST']._serialized_start=118
  _globals['_ENDPRAYERREQUEST']._serialized_end=153
  _globals['_ENDPRAYERRESPONSE']._serialized_start=155
  _globals['_ENDPRAYERRESPONSE']._serialized_end=191
  _globals['_PRAYERUPDATESREQUEST']._serialized_start=193
  _globals['_PRAYERUPDATESREQUEST']._serialized_end=232
  _globals['_PRAYERUPDATERESPONSE']._serialized_start=234
  _globals['_PRAYERUPDATERESPONSE']._serialized_end=329
  _globals['_PRAYERDURATIONREQUEST']._serialized_start=331
  _globals['_PRAYERDURATIONREQUEST']._serialized_end=371
  _globals['_PRAYERDURATIONRESPONSE']._serialized_start=373
  _globals['_PRAYERDURATIONRESPONSE']._serialized_end=415
  _globals['_VOICEDURATIONREQUEST']._serialized_start=417
  _globals['_VOICEDURATIONREQUEST']._serialized_end=456
  _globals['_VOICEDURATIONRESPONSE']._serialized_start=458
  _globals['_VOICEDURATIONRESPONSE']._serialized_end=499
  _globals['_PRAYERTRACKER']._serialized_start=502
  _globals['_PRAYERTRACKER']._serialized_end=963
# @@protoc_insertion_point(module_scope)
