# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

# import bible_service_pb2 as bible__service__pb2
from . import bible_service_pb2 as bible__service__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class BibleServiceStub(object):
    """Service for accessing Bible data
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetBibleVersions = channel.unary_unary(
                '/dbibles.BibleService/GetBibleVersions',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=bible__service__pb2.BibleVersionList.FromString,
                )
        self.GetBooksInVersion = channel.unary_unary(
                '/dbibles.BibleService/GetBooksInVersion',
                request_serializer=bible__service__pb2.BibleVersionRequest.SerializeToString,
                response_deserializer=bible__service__pb2.BibleBookList.FromString,
                )
        self.GetChaptersInBook = channel.unary_unary(
                '/dbibles.BibleService/GetChaptersInBook',
                request_serializer=bible__service__pb2.BibleBookRequest.SerializeToString,
                response_deserializer=bible__service__pb2.BibleChapterList.FromString,
                )
        self.GetVerse = channel.unary_unary(
                '/dbibles.BibleService/GetVerse',
                request_serializer=bible__service__pb2.BibleVerseRequest.SerializeToString,
                response_deserializer=bible__service__pb2.BibleVerseResponse.FromString,
                )


class BibleServiceServicer(object):
    """Service for accessing Bible data
    """

    def GetBibleVersions(self, request, context):
        """Get a list of available Bible versions
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBooksInVersion(self, request, context):
        """Get a list of books in a specific Bible version
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetChaptersInBook(self, request, context):
        """Get a list of chapters in a specific book
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVerse(self, request, context):
        """Get the content of a specific verse
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BibleServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetBibleVersions': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBibleVersions,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=bible__service__pb2.BibleVersionList.SerializeToString,
            ),
            'GetBooksInVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBooksInVersion,
                    request_deserializer=bible__service__pb2.BibleVersionRequest.FromString,
                    response_serializer=bible__service__pb2.BibleBookList.SerializeToString,
            ),
            'GetChaptersInBook': grpc.unary_unary_rpc_method_handler(
                    servicer.GetChaptersInBook,
                    request_deserializer=bible__service__pb2.BibleBookRequest.FromString,
                    response_serializer=bible__service__pb2.BibleChapterList.SerializeToString,
            ),
            'GetVerse': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVerse,
                    request_deserializer=bible__service__pb2.BibleVerseRequest.FromString,
                    response_serializer=bible__service__pb2.BibleVerseResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dbibles.BibleService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BibleService(object):
    """Service for accessing Bible data
    """

    @staticmethod
    def GetBibleVersions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dbibles.BibleService/GetBibleVersions',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            bible__service__pb2.BibleVersionList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetBooksInVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dbibles.BibleService/GetBooksInVersion',
            bible__service__pb2.BibleVersionRequest.SerializeToString,
            bible__service__pb2.BibleBookList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetChaptersInBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dbibles.BibleService/GetChaptersInBook',
            bible__service__pb2.BibleBookRequest.SerializeToString,
            bible__service__pb2.BibleChapterList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetVerse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/dbibles.BibleService/GetVerse',
            bible__service__pb2.BibleVerseRequest.SerializeToString,
            bible__service__pb2.BibleVerseResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
